### PR TITLE
some ca65 fixes, part 2

### PR DESCRIPTION
**Pull request by freem**
more changes for ca65 compatibility...
There's more to come, but a couple things that need to get done would cause incompatibilities with pceas, so I'm not sure of the best way to go about it.

### CODE REVIEW

**Comment by freem** [comment]
something I just realized is that ca65 will flip out if two sources have the same filename (like how the current /include/ca65 directory is set up)... argh

e.g. there's `include/memcpy.inc` and `include/ca65/memcpy.inc`; if I set the include directory to `include` via `-I` and just try to `.include "memcpy.inc"`, it will include the one in the ca65 folder instead of the base folder.

**Comment by BlockoS** [comment]
Hum... that's weird.
Anyway my plan was to have a preprocessor variable telling which compiler is being used and then pick the right directory (ca65 or pceas). This way, we will have something like this in memcpy.inc:
```asm
  .if (__ASM__ = __CA65__)
    .include "ca65/memcpy.inc"
  .elseif(__ASM__ = __PCEAS__)
    .include "pceas/memcpy.inc"
  .else
    .fail "Unsupported assembler! Only pceas and ca65 are supported for the moment."
  .endif
```
But if ca65 is searching by itself in the subdirectories we are screwed :confused: 
Your solution will do the trick.

**Comment by BlockoS** [comment]
I made a small test, and it seems to work when I invoke ca65 (fresh compilation from the master branch) with -I include... That's weird.

**Comment by freem** [comment]
well I'm fucked then because it's still doing the same thing even with a new checkout
[freem_example.zip](https://github.com/BlockoS/HuDK/files/151868/freem_example.zip)

**Comment by BlockoS** [comment]
I found a workaround... and it's ugly...
In include/ca65/start.s : 
```asm
    .include "ca65/word.inc"                                                                                  
    .include "ca65/memcpy.inc"                                                                                
    .include "system.inc"                                                                                     
    .include "ca65/../memcpy.inc"                                                                             
    .include "ca65/../irq.inc"                                                                                
    .include "io.inc"                                                                                         
    .include "psg.inc"                                                                                        
    .include "ca65/../vdc.inc"                                                                                
    .include "vce.inc"                                                                                        
    .include "ca65/irq.inc"                                                                                   
    .include "ca65/vdc.inc"
```

**Comment by BlockoS** [comment]
In my opinion, it was including the same file twice as it first searches locally, then goes to the include search paths. I think pceas is working thanks to some side-effect in the include paths management.

**Pull request merged**
